language: node_js
node_js:
  - 11.12.0
cache: npm

branches:
  except:
  - master

before_install:
  - npm install
  - rvm install 2.3.1
  - rvm use 2.3.1
  - gem install bundler
deploy:
  provider: script
  script: "./_scripts/build.sh"
  skip_cleanup: false
  on:
    branch: dev
