language: node_js
node_js:
  - 11.12.0
cache: npm

install:
  - npm install

script:
  - npm run deploy

before_deploy:
  - ls | grep -v _site | xargs rm -rf

deploy:
  provider: script
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  local_dir: _site
  on:
    branch: master
