language: node_js
node_js:
  - 11.12.0
cache: yarn

install:
  - npm install

script:
  - npm run build

  deploy:
    provider: script
    skip-cleanup: true
    github-token: $GITHUB_TOKEN
    local_dir: _sites
    on:
      branch: master
